spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=ecommerce
spring.datasource.password=ecommerce
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.security.user.name=user
spring.security.user.password=12345

jwt.secret=HGG&&*nghVHJG%fye92u284fu1lpll!@#$%SRTYUIKJGFD#$%&UJNBVCDR%&

stripe.secret-key=sk_test_51UGTD2RtXMT6Q1WzFdeLzpjvSHcCanm1OV3TzAG0uiniSrcd0VI22YamTB3BSLOzKtPkCdJpHnKByeAL9c9aTnCj00xt4hbzPv
stripe.webhook-secret=whsec_c1f3fa4d60ff51706dd7b699e28e1c5ef5882129a8dc6f312cdc298c6b878bd0